language: node_js
sudo: false
env:
- CXX=g++-4.8
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- '5'
git:
  submodules: false

before_install:

before_script:
- npm install -g retire


